### ISSUE TITLE
ライセンスの設定

### ISSUE THREAD

**Issue by Foo-x** [t0m0120/IshikawaTakidashiMap#8]
素晴らしいプロジェクトを立ち上げていただきありがとうございます。
スキルセット的に微力ながらお手伝いできそうです。
ただ、現状では複製・改変の許可が明示されていないため、ライセンスを設定いただけると幸いです。

**Comment by t0m0120** [comment]
@Foo-x 
Issue起票ありがとうございます 🙇 

MITライセンスを設定しました。
この課題はCloseとします！
